# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25a960a88fedda281935358401e3357fadd034cb697a0aeb42b7022fae0f4490ba766ec5e9dee96618a72c68da56f6ac12eaf3ba31911beb172ec6fb50c23dd

test:
  secret_key_base: 85df67c0bab1280286b01f9a4dd791ada0181c7121cff27b434f554ca13130e5a690ff2de9bbcca99e99209ffb928a6278d03ccd172284f0a7d3ae50768bd72a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
